source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ReaXn_Example', :exclusive => true do
  pod "ReaXn", :path => "../"
end

target 'ReaXn_Tests', :exclusive => true do
  pod "ReaXn", :path => "../"

  
end
